@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    enum "<size:14>TripStatus\n<size:10>CarSharing.provided" as CarSharing.provided.TripStatus [[TripStatus.html]] {
        {static} +CREATED
        {static} +STARTED
        {static} +COMPLETED
    }

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
