@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>QuickFormat\n<size:10>CarSharing.util" as CarSharing.util.QuickFormat [[QuickFormat.html]] {
        +format(Trip): String
    }

    abstract class "<size:14>Formatter\n<size:10>CarSharing.provided" as CarSharing.provided.Formatter<Trip> [[../provided/Formatter.html]] {
        {abstract} +format(Trip): String
    }

    CarSharing.provided.Formatter <|-- CarSharing.util.QuickFormat

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
