@startuml
    set namespaceSeparator none
    hide empty fields
    hide empty methods

    class "<size:14>StatusComparator\n<size:10>CarSharing.util" as CarSharing.util.StatusComparator [[StatusComparator.html]] {
        +compare(Trip, Trip): int
    }

    interface "<size:14>Comparator\n<size:10>java.util" as java.util.Comparator<Trip> {
        {abstract} +compare(Trip, Trip): int
    }

    java.util.Comparator <|.. CarSharing.util.StatusComparator

    center footer UMLDoclet 2.0.12, PlantUML 1.2020.16
@enduml
